In [1]:
pip install numpy

^C
Note: you may need to restart the kernel to use updated packages.


   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   -----------------


[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np


In [5]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

In [9]:
np_height = np.array(height)
np_weight = np.array(weight)
np_h_w=np.stack((np_height,np_weight),axis=1)
print( (np_h_w))

[[ 1.73 65.4 ]
 [ 1.68 59.2 ]
 [ 1.71 63.6 ]
 [ 1.89 88.4 ]
 [ 1.79 68.7 ]]


In [5]:
bmi = np_weight / np_height ** 2

In [6]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [7]:
bmi[bmi>20]

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [8]:
bmi[bmi<20]

array([], dtype=float64)

In [9]:
print(bmi[bmi>22])

[24.7473475]


In [10]:
bmii=np.array([22,33,33,22,11,33])

In [11]:
print(bmii[bmii>22])

[33 33 33]


In [16]:
bmii[bmii==22]=33

In [13]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [17]:
bmii

array([33, 33, 33, 33, 11, 33])

In [18]:
type(bmii)

numpy.ndarray

In [1]:
heights=np.array([33,44,34.6,22.6,44.8])
heights

NameError: name 'np' is not defined