In [1]:
pip show numpy

Name: numpy
Version: 2.5.0
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License-Expression: BSD-3-Clause AND 0BSD AND MIT AND Zlib AND CC0-1.0
Location: c:\Users\akmal\AppData\Local\Programs\Python\Python313\Lib\site-packages
Requires: 
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
number=np.array([10,20,30,40,50])

In [ ]:
print(number.sum())

150


In [6]:
print(number.shape)

(5,)


In [7]:
print(type(number))

<class 'numpy.ndarray'>


In [8]:
print(number.dtype)

int64


In [10]:
array_2d=np.array([[11,22,33,44],[66,77,88,99],[90,80,70,60]])

In [11]:
array_2d

array([[11, 22, 33, 44],
       [66, 77, 88, 99],
       [90, 80, 70, 60]])

In [28]:
array_2d.shape


(3, 4)

In [17]:
zeros=np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
ones=np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
idenity=np.eye(5)
print(idenity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
digits=np.arange(0,20,2)
print(digits)

[ 0  2  4  6  8 10 12 14 16 18]


In [26]:
digitss=np.linspace(0,20,5)
print(digitss)

[ 0.  5. 10. 15. 20.]
